openapi: 3.0.2
info:
  title: realms Basic API
  version: '1.0'
  contact:
    name: Beamable Support
    url: https://api.beamable.com
    email: support@beamable.com
servers:
- url: https://api.beamable.com
security: []
tags:
- name: Basic
paths:
  /basic/realms/customer/activate:
    get:
      security:
      - {}
      tags:
      - Basic
  /basic/realms/project/beamable:
    post:
      security:
      - user:
        - developer
      - server: []
      tags:
      - Basic
  /basic/realms/customer/alias/available:
    get:
      security:
      - {}
      tags:
      - Basic
  /basic/realms/project:
    get:
      security:
      - {}
      tags:
      - Basic
    post:
      security:
      - user:
        - developer
      - server: []
      tags:
      - Basic
    put:
      security:
      - user:
        - developer
      - server: []
      tags:
      - Basic
    delete:
      security:
      - user:
        - developer
      - server: []
      tags:
      - Basic
  /basic/realms/customer/verify:
    post:
      security:
      - {}
      tags:
      - Basic
  /basic/realms/games:
    get:
      security:
      - user:
        - tester
      - server: []
      tags:
      - Basic
  /basic/realms/config:
    get:
      security:
      - user:
        - tester
      - server: []
      tags:
      - Basic
    post:
      security:
      - user:
        - developer
      - server: []
      tags:
      - Basic
    put:
      security:
      - user:
        - developer
      - server: []
      tags:
      - Basic
  /basic/realms/project/rename:
    put:
      security:
      - user:
        - developer
      - server: []
      tags:
      - Basic
  /basic/realms/plans:
    get:
      security:
      - user:
        - tester
      - server: []
      tags:
      - Basic
    post:
      security:
      - user:
        - developer
      - server: []
      tags:
      - Basic
  /basic/realms/client/defaults:
    get:
      security:
      - {}
      tags:
      - Basic
  /basic/realms/customer:
    get:
      security:
      - user:
        - tester
      - server: []
      tags:
      - Basic
    post:
      security:
      - {}
      tags:
      - Basic
  /basic/realms/admin/inflight/failures:
    get:
      security:
      - user:
        - developer
      - server: []
      tags:
      - Basic
    delete:
      security:
      - user:
        - developer
      - server: []
      tags:
      - Basic
  /basic/realms/launch-message:
    get:
      security:
      - user:
        - tester
      - server: []
      tags:
      - Basic
    post:
      security:
      - user:
        - developer
      - server: []
      tags:
      - Basic
    delete:
      security:
      - user:
        - developer
      - server: []
      tags:
      - Basic
  /basic/realms/is-customer:
    get:
      security:
      - {}
      tags:
      - Basic
  /basic/realms/admin/customer:
    get:
      security:
      - user:
        - developer
      - server: []
      tags:
      - Basic
  /basic/realms/game:
    get:
      security:
      - user:
        - tester
      - server: []
      tags:
      - Basic
    post:
      security:
      - user:
        - developer
      - server: []
      tags:
      - Basic
    put:
      security:
      - user:
        - developer
      - server: []
      tags:
      - Basic
  /basic/realms/project/promote:
    get:
      security:
      - user:
        - tester
      - server: []
      tags:
      - Basic
    post:
      security:
      - user:
        - developer
      - server: []
      tags:
      - Basic
  /basic/realms/customers:
    get:
      security:
      - {}
      tags:
      - Basic
  /basic/realms/promotion:
    get:
      security:
      - user:
        - tester
      - server: []
      tags:
      - Basic
    post:
      security:
      - user:
        - developer
      - server: []
      tags:
      - Basic
  /basic/beamo/microservice/registrations:
    post:
      security:
      - user:
        - tester
      - server: []
      tags:
      - Basic
  /basic/beamo/microservice/federation/traffic:
    put:
      security:
      - user:
        - developer
      - server: []
      tags:
      - Basic
    delete:
      security:
      - user:
        - developer
      - server: []
      tags:
      - Basic
  /basic/beamo/image/urls:
    post:
      security:
      - user:
        - developer
      - server: []
      tags:
      - Basic
  /basic/beamo/metricsUrl:
    post:
      security:
      - user:
        - tester
      - server: []
      tags:
      - Basic
  /basic/beamo/microservice/secret:
    get:
      security:
      - user:
        - admin
      - server: []
      tags:
      - Basic
  /basic/beamo/queryLogs/result:
    post:
      security:
      - user:
        - tester
      - server: []
      tags:
      - Basic
  /basic/beamo/storage/performance:
    get:
      security:
      - user:
        - admin
      - server: []
      tags:
      - Basic
  /basic/beamo/manifests:
    get:
      security:
      - user:
        - tester
      - server: []
      tags:
      - Basic
  /basic/beamo/templates:
    get:
      security:
      - user:
        - tester
      - server: []
      tags:
      - Basic
  /basic/beamo/queryLogs:
    post:
      security:
      - user:
        - tester
      - server: []
      tags:
      - Basic
    delete:
      security:
      - user:
        - tester
      - server: []
      tags:
      - Basic
  /basic/beamo/logsUrl:
    post:
      security:
      - user:
        - tester
      - server: []
      tags:
      - Basic
  /basic/beamo/image/commit:
    put:
      security:
      - user:
        - developer
      - server: []
      tags:
      - Basic
  /basic/beamo/uploadAPI:
    get:
      security:
      - user:
        - tester
      - server: []
      tags:
      - Basic
  /basic/beamo/status:
    get:
      security:
      - user:
        - tester
      - server: []
      tags:
      - Basic
  /basic/beamo/manifest/current:
    get:
      security:
      - user:
        - tester
      - server: []
      tags:
      - Basic
  /basic/beamo/manifest/pull:
    post:
      security:
      - user:
        - developer
      - server: []
      tags:
      - Basic
  /basic/beamo/registry:
    get:
      security:
      - user:
        - tester
      - server: []
      tags:
      - Basic
  /basic/beamo/manifest/deploy:
    post:
      security:
      - user:
        - developer
      - server: []
      tags:
      - Basic
  /basic/beamo/microservice/federation:
    post:
      security:
      - user:
        - tester
      - server: []
      tags:
      - Basic
  /basic/beamo/storage/connection:
    get:
      security:
      - user:
        - admin
      - server: []
      tags:
      - Basic
  /basic/beamo/manifest:
    get:
      security:
      - user:
        - tester
      - server: []
      tags:
      - Basic
    post:
      security:
      - user:
        - developer
      - server: []
      tags:
      - Basic
  /basic/auth/token/list:
    get:
      security:
      - user:
        - developer
      - server: []
      tags:
      - Basic
  /basic/auth/token:
    get:
      security:
      - {}
      tags:
      - Basic
    post:
      security:
      - {}
      tags:
      - Basic
  /basic/auth/token/revoke:
    put:
      security:
      - user:
        - developer
      - server: []
      tags:
      - Basic
components:
  securitySchemes:
    server:
      type: apiKey
      name: X-DE-SIGNATURE
      in: header
      description: Signed Request authentication using project secret key.
    user:
      type: http
      description: Bearer authentication with a player access token in the Authorization header.
      scheme: bearer
      bearerFormat: Bearer <Access Token>